pipeline {
    agent any

    environment {
        VENV_DIR = 'venv'
        DOCKER_HUB_REPO = "collinsthegr8/messaging-app"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/collinsthegreat/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Setup Python') {
            steps {
                sh '''
                python3 -m venv ${VENV_DIR}
                . ${VENV_DIR}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Lint') {
            steps {
                sh '''
                . ${VENV_DIR}/bin/activate
                pip3 install flake8
                flake8 messaging_app
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . ${VENV_DIR}/bin/activate
                pip3 install pytest pytest-cov
                pytest messaging_app/tests --cov=messaging_app --cov-report=xml --cov-report=term
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t ${DOCKER_HUB_REPO}:latest messaging_app/
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds',
                                                 usernameVariable: 'DOCKER_USER',
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push ${DOCKER_HUB_REPO}:latest
                    '''
                }
            }
        }
    }

    post {
        always {
            sh "rm -rf ${VENV_DIR} || true"
        }
    }
}
