pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = credentials('github-creds')
        VENV_DIR = 'venv'
    }

    stages {      
        stage('Checkout') {
        steps {
            git branch: 'main',
                url: 'https://github.com/collinsthegreat/alx-backend-python.git',
                credentialsId: 'github-creds'
        }
}


        stage('Setup Python') {
            steps {
                sh '''
                python3 -m venv ${VENV_DIR}
                . ${VENV_DIR}/bin/activate
                pip install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . ${VENV_DIR}/bin/activate
                pytest messaging_app/tests --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }

}
