pipeline {
    agent any

    environment {
        GITHUB_CREDENTIALS = credentials('github-creds')
        VENV_DIR = 'venv'
        DOCKER_HUB_REPO = "collinsthegr8/messaging-app"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/collinsthegreat/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Setup Python & Run Tests') {
            agent {
                docker { image 'python:3.10' }
            }
            steps {
                sh '''
                python3 -m venv ${VENV_DIR}
                . ${VENV_DIR}/bin/activate
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                pytest messaging_app/tests --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }

        stage('Build Docker Image') {
            agent any
            steps {
                sh '''
                docker build -t ${DOCKER_HUB_REPO}:latest messaging_app/
                '''
            }
        }

        stage('Push Docker Image') {
            agent any
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds',
                                                 usernameVariable: 'DOCKER_USER',
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push ${DOCKER_HUB_REPO}:latest
                    '''
                }
            }
        }
    }
}
