name: Django CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'messaging_app/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'messaging_app/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password_123
          MYSQL_DATABASE: messaging_app_test_db
          MYSQL_USER: messaging_user
          MYSQL_PASSWORD: messaging_password_123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DJANGO_SETTINGS_MODULE: messaging_app.settings
      MYSQL_DATABASE: messaging_app_test_db
      MYSQL_USER: messaging_user
      MYSQL_PASSWORD: messaging_password_123
      MYSQL_ROOT_PASSWORD: root_password_123
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      SECRET_KEY: test-secret-key-for-github-actions
      DEBUG: False

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('messaging_app/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          default-mysql-client \
          default-libmysqlclient-dev \
          gcc \
          pkg-config

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r messaging_app/requirements.txt
        pip install -r messaging_app/requirements-dev.txt

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h127.0.0.1 -P3306 -umessaging_user -pmessaging_password_123 --silent; do
          echo "Waiting for MySQL..."
          sleep 2
        done
        echo "✅ MySQL is ready!"

    - name: Run migrations
      run: |
        cd messaging_app
        python manage.py migrate --settings=messaging_app.settings

    - name: Run linting (flake8)
      run: |
        cd messaging_app
        flake8 --max-line-length=88 --exclude=venv,migrations,__pycache__,.git --statistics .

    - name: Run Django tests with coverage
      run: |
        cd messaging_app
        coverage run --source='.' manage.py test --verbosity=2 --keepdb
        coverage report
        coverage xml -o coverage.xml

    - name: Run pytest (extra tests)
      run: |
        cd messaging_app
        pytest test_*.py -v \
          --junitxml=test_results.xml \
          --cov=. \
          --cov-report=xml:coverage.xml \
          --cov-report=term \
          --tb=short

    - name: Upload test results & coverage
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-python-${{ matrix.python-version }}
        path: |
          messaging_app/test_results.xml
          messaging_app/coverage.xml
        retention-days: 30

    - name: Upload to Codecov
      uses: codecov/codecov-action@v3
      if: matrix.python-version == '3.10'
      with:
        file: messaging_app/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        cd messaging_app
        black --check --diff .
        isort --check-only --diff .
        flake8 --max-line-length=88 --exclude=venv,migrations,__pycache__,.git --statistics .

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        cd messaging_app
        bandit -r . -x tests/ -f json -o bandit-report.json || true
        safety check --json --output safety-report.json || true
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-reports
        path: |
          messaging_app/bandit-report.json
          messaging_app/safety-report.json
