apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messaging-db
  template:
    metadata:
      labels:
        app: messaging-db
    spec:
      containers:
        - name: messaging-db
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "messaging_app_db"
            - name: POSTGRES_USER
              value: "messaging_user"
            - name: POSTGRES_PASSWORD
              value: "secure_password_123"
---
apiVersion: v1
kind: Service
metadata:
  name: db   # This is the hostname Django will use
spec:
  selector:
    app: messaging-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
